api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld:    ['application/ld+json']
        jsonhal:   ['application/hal+json']
        jsonapi:   ['application/vnd.api+json']
        json:      ['application/json']
        xml:       ['application/xml', 'text/xml']
        yaml:      ['application/x-yaml']
        csv:       ['text/csv']
        html:      ['text/html']
        geojson:   ['application/vnd.geo+json']
        jsonpatch: ['application/json-patch+json']
        pdf:       ['application/pdf']
    patch_formats:
        json:      ['application/json']
        jsonld:    ['application/ld+json']
        jsonpatch: ['application/json-patch+json']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
    exception_to_status:
        App\Security\User\UnloggedAccessException: 403
    eager_loading:
        max_joins: 300