<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.event.listener.occurrence.event.listener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EventListener/OccurrenceEventListener.php';

return $this->privates['app.event.listener.occurrence.event.listener'] = new \App\EventListener\OccurrenceEventListener(($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
