<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.event.listener.photo.event.listener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EventListener/PhotoEventListener.php';

return $this->privates['app.event.listener.photo.event.listener'] = new \App\EventListener\PhotoEventListener(($this->privates['router.request_context'] ?? $this->getRouter_RequestContextService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
