<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.event.listener.pdf.file.event.listener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EventListener/PdfFileEventListener.php';

return $this->privates['app.event.listener.pdf.file.event.listener'] = new \App\EventListener\PdfFileEventListener(($this->services['vich_uploader.templating.helper.uploader_helper'] ?? $this->getVichUploader_Templating_Helper_UploaderHelperService()), ($this->privates['router.request_context'] ?? $this->getRouter_RequestContextService()));
