<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\CreatePhotoAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/CreatePhotoAction.php';

return $this->services['App\\Controller\\CreatePhotoAction'] = new \App\Controller\CreatePhotoAction(($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->privates['security.helper'] ?? $this->getSecurity_HelperService()), ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['validator'] ?? $this->getValidatorService()));
