<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easy_deploy.command.deploy' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/easycorp/easy-deploy-bundle/src/Command/DeployCommand.php';

$this->privates['easy_deploy.command.deploy'] = $instance = new \EasyCorp\Bundle\EasyDeployBundle\Command\DeployCommand(($this->privates['file_locator'] ?? $this->load('getFileLocatorService.php')), (($this->hasParameter("kernel.project_dir")) ? ($this->getParameter("kernel.project_dir")) : (($this->getParameter("kernel.root_dir") . "/.."))), (\dirname(__DIR__, 3).'/log'));

$instance->setName('deploy');

return $instance;
