<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ExportOccurrenceAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/ExportOccurrenceAction.php';
include_once \dirname(__DIR__, 4).'/src/Service/ExportOccurrenceService.php';

return $this->services['App\\Controller\\ExportOccurrenceAction'] = new \App\Controller\ExportOccurrenceAction(new \App\Service\ExportOccurrenceService(($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService())));
