<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue_elastica.populate_processor' shared service.

include_once \dirname(__DIR__, 4).'/vendor/queue-interop/queue-interop/src/Processor.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/CommandSubscriberInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/QueueSubscriberInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/elastica-bundle/Queue/PopulateProcessor.php';

return $this->privates['enqueue_elastica.populate_processor'] = new \Enqueue\ElasticaBundle\Queue\PopulateProcessor(($this->services['fos_elastica.pager_provider_registry'] ?? $this->load('getFosElastica_PagerProviderRegistryService.php')), ($this->services['fos_elastica.pager_persister_registry'] ?? $this->load('getFosElastica_PagerPersisterRegistryService.php')));
