<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.default.spool_producer' shared service.

include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/SpoolProducer.php';

return $this->privates['enqueue.client.default.spool_producer'] = new \Enqueue\Client\SpoolProducer(($this->privates['enqueue.client.default.lazy_producer'] ?? $this->load('getEnqueue_Client_Default_LazyProducerService.php')));
