<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.consume_command' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Consumption/LimitsExtensionsCommandTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Client/SetupBrokerExtensionCommandTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Consumption/QueueConsumerOptionsCommandTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Consumption/ChooseLoggerCommandTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Client/ConsumeCommand.php';

$this->privates['enqueue.client.consume_command'] = $instance = new \Enqueue\Symfony\Client\ConsumeCommand(($this->privates['enqueue.locator'] ?? $this->load('getEnqueue_LocatorService.php')), 'default', 'enqueue.client.%s.queue_consumer', 'enqueue.client.%s.driver', 'enqueue.client.%s.delegate_processor');

$instance->setName('enqueue:consume');

return $instance;
