<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.index_manager' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Index/IndexManager.php';

$a = ($this->services['fos_elastica.index.occurrences'] ?? $this->getFosElastica_Index_OccurrencesService());

return $this->services['fos_elastica.index_manager'] = new \FOS\ElasticaBundle\Index\IndexManager(['occurrences' => $a, 'photos' => ($this->services['fos_elastica.index.photos'] ?? $this->getFosElastica_Index_PhotosService()), 'tables' => ($this->services['fos_elastica.index.tables'] ?? $this->getFosElastica_Index_TablesService()), 'observers' => ($this->services['fos_elastica.index.observers'] ?? $this->getFosElastica_Index_ObserversService()), 'biblio_phytos' => ($this->services['fos_elastica.index.biblio_phytos'] ?? $this->getFosElastica_Index_BiblioPhytosService())], $a);
