<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.object_persister.photos.photo' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersisterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersister.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/ModelToElasticaTransformerInterface.php';
include_once \dirname(__DIR__, 4).'/src/Elastica/Transformer/PhotoToElasticaTransformer.php';

return $this->services['fos_elastica.object_persister.photos.photo'] = new \FOS\ElasticaBundle\Persister\ObjectPersister(($this->services['fos_elastica.index.photos.photo'] ?? $this->getFosElastica_Index_Photos_PhotoService()), new \App\Elastica\Transformer\PhotoToElasticaTransformer(), 'App\\Entity\\Photo', ['userId' => ['type' => 'long'], 'userEmail' => [], 'userPseudo' => [], 'originalName' => [], 'dateShot' => ['type' => 'date', 'format' => 'yyyy-MM-dd HH:mm:ss'], 'dateShot_keyword' => ['type' => 'keyword'], 'dateShotYear' => ['type' => 'long'], 'dateShotMonth' => ['type' => 'long'], 'dateShotDay' => ['type' => 'long'], 'dateObserved' => ['type' => 'date', 'format' => 'yyyy-MM-dd HH:mm:ss'], 'dateObservedYear' => ['type' => 'long'], 'dateObservedMonth' => ['type' => 'long'], 'dateObservedDay' => ['type' => 'long'], 'dateCreated' => ['type' => 'date', 'format' => 'yyyy-MM-dd HH:mm:ss'], 'dateCreated_keyword' => ['type' => 'keyword'], 'dateUpdated' => ['type' => 'date', 'format' => 'yyyy-MM-dd HH:mm:ss'], 'userSciName' => [], 'userSciNameId' => ['type' => 'long'], 'family' => ['type' => 'text'], 'family_keyword' => ['type' => 'keyword'], 'certainty' => ['type' => 'text'], 'certainty_keyword' => ['type' => 'keyword'], 'isPublic' => ['type' => 'boolean'], 'locality' => ['type' => 'text'], 'frenchDep' => ['type' => 'long'], 'locality_keyword' => ['type' => 'keyword'], 'osmCounty' => [], 'osmCountry' => [], 'osmCountryCode' => [], 'projectId' => ['type' => 'long'], 'tags' => []], []);
