<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.filter_objects_listener' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/Listener/FilterObjectsListener.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/IndexableInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/Indexable.php';

return $this->services['fos_elastica.filter_objects_listener'] = new \FOS\ElasticaBundle\Persister\Listener\FilterObjectsListener(($this->privates['fos_elastica.indexable'] ?? ($this->privates['fos_elastica.indexable'] = new \FOS\ElasticaBundle\Provider\Indexable([]))));
