<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_elastica.listener.occurrences.occurrence' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/Listener.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/IndexableInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/Indexable.php';

return $this->privates['fos_elastica.listener.occurrences.occurrence'] = new \FOS\ElasticaBundle\Doctrine\Listener(($this->services['fos_elastica.object_persister.occurrences.occurrence'] ?? $this->load('getFosElastica_ObjectPersister_Occurrences_OccurrenceService.php')), ($this->privates['fos_elastica.indexable'] ?? ($this->privates['fos_elastica.indexable'] = new \FOS\ElasticaBundle\Provider\Indexable([]))), ['identifier' => 'id', 'indexName' => 'occurrences', 'typeName' => 'occurrence'], NULL);
