<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.pager_provider_registry' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/PagerProviderRegistry.php';

$this->services['fos_elastica.pager_provider_registry'] = $instance = new \FOS\ElasticaBundle\Provider\PagerProviderRegistry(['occurrences' => ['occurrence' => 'fos_elastica.pager_provider.occurrences.occurrence'], 'photos' => ['photo' => 'fos_elastica.pager_provider.photos.photo'], 'tables' => ['table' => 'fos_elastica.pager_provider.tables.table'], 'observers' => ['observer' => 'fos_elastica.pager_provider.observers.observer'], 'biblio_phytos' => ['biblio_phyto' => 'fos_elastica.pager_provider.biblio_phytos.biblio_phyto']]);

$instance->setContainer($this);

return $instance;
