<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ImportOccurrenceAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/ImportOccurrenceAction.php';

return $this->services['App\\Controller\\ImportOccurrenceAction'] = new \App\Controller\ImportOccurrenceAction(($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()), ($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->services['validator'] ?? $this->getValidatorService()));
