<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.voter.App\Security\Authorization\PhotoVoter' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/Authorization/Voter/VoterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/Authorization/Voter/TraceableVoter.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/Authorization/Voter/Voter.php';
include_once \dirname(__DIR__, 4).'/src/Security/Authorization/AbstractVoter.php';
include_once \dirname(__DIR__, 4).'/src/Security/Authorization/OccurrenceVoter.php';
include_once \dirname(__DIR__, 4).'/src/Security/Authorization/PhotoVoter.php';

return $this->privates['debug.security.voter.App\\Security\\Authorization\\PhotoVoter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \App\Security\Authorization\PhotoVoter(), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
