<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.guard.main' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/Authentication/Provider/AuthenticationProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Guard/Provider/GuardAuthenticationProvider.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/User/UserCheckerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/User/UserChecker.php';

return $this->privates['security.authentication.provider.guard.main'] = new \Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider(new RewindableGenerator(function () {
    yield 0 => ($this->privates['App\\Security\\SSOAuthenticator'] ?? ($this->privates['App\\Security\\SSOAuthenticator'] = new \App\Security\SSOAuthenticator()));
}, 1), ($this->privates['App\\Security\\SSOUserProvider'] ?? $this->load('getSSOUserProviderService.php')), 'main', new \Symfony\Component\Security\Core\User\UserChecker(), ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php')));
