<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.event.listener.occurrence.user.occurrence.tag.relation.event.listener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EventListener/OccurrenceUserOccurrenceTagRelationEventListener.php';

return $this->privates['app.event.listener.occurrence.user.occurrence.tag.relation.event.listener'] = new \App\EventListener\OccurrenceUserOccurrenceTagRelationEventListener(($this->services['fos_elastica.object_persister.occurrences.occurrence'] ?? $this->load('getFosElastica_ObjectPersister_Occurrences_OccurrenceService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
