<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.event.listener.timestamped.entity.event.listener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EventListener/TimestampedEntityEventListener.php';

return $this->privates['app.event.listener.timestamped.entity.event.listener'] = new \App\EventListener\TimestampedEntityEventListener();
