<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.event.listener.photo.photo.tag.relation.event.listener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EventListener/PhotoPhotoTagRelationEventListener.php';

return $this->privates['app.event.listener.photo.photo.tag.relation.event.listener'] = new \App\EventListener\PhotoPhotoTagRelationEventListener(($this->services['fos_elastica.object_persister.photos.photo'] ?? $this->load('getFosElastica_ObjectPersister_Photos_PhotoService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
