<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.event.listener.owned.entity.event.listener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EventListener/OwnedEntityEventListener.php';

return $this->privates['app.event.listener.owned.entity.event.listener'] = new \App\EventListener\OwnedEntityEventListener(($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()));
