<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.transport.default.processor_registry' shared service.

include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/ProcessorRegistryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/ContainerProcessorRegistry.php';

return $this->privates['enqueue.transport.default.processor_registry'] = new \Enqueue\Symfony\ContainerProcessorRegistry((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'enqueue_elastica.populate_processor' => ['privates', 'enqueue_elastica.populate_processor', 'getEnqueueElastica_PopulateProcessorService.php', true],
], [
    'enqueue_elastica.populate_processor' => '?',
]))->withContext('enqueue.transport.default.processor_registry', $this));
