<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.locator' shared service.

return $this->privates['enqueue.locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'enqueue.client.default.delegate_processor' => ['privates', 'enqueue.client.default.delegate_processor', 'getEnqueue_Client_Default_DelegateProcessorService.php', true],
    'enqueue.client.default.driver' => ['privates', 'enqueue.client.default.driver', 'getEnqueue_Client_Default_DriverService.php', true],
    'enqueue.client.default.producer' => ['privates', 'enqueue.client.default.lazy_producer', 'getEnqueue_Client_Default_LazyProducerService.php', true],
    'enqueue.client.default.queue_consumer' => ['privates', 'enqueue.client.default.queue_consumer', 'getEnqueue_Client_Default_QueueConsumerService.php', true],
    'enqueue.transport.default.context' => ['privates', 'enqueue.transport.default.context', 'getEnqueue_Transport_Default_ContextService.php', true],
    'enqueue.transport.default.processor_registry' => ['privates', 'enqueue.transport.default.processor_registry', 'getEnqueue_Transport_Default_ProcessorRegistryService.php', true],
    'enqueue.transport.default.queue_consumer' => ['privates', 'enqueue.transport.default.queue_consumer', 'getEnqueue_Transport_Default_QueueConsumerService.php', true],
], [
    'enqueue.client.default.delegate_processor' => '?',
    'enqueue.client.default.driver' => '?',
    'enqueue.client.default.producer' => '?',
    'enqueue.client.default.queue_consumer' => '?',
    'enqueue.transport.default.context' => '?',
    'enqueue.transport.default.processor_registry' => '?',
    'enqueue.transport.default.queue_consumer' => '?',
]);
