<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.routes_command' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Client/RoutesCommand.php';

$this->privates['enqueue.client.routes_command'] = $instance = new \Enqueue\Symfony\Client\RoutesCommand(($this->privates['enqueue.locator'] ?? $this->load('getEnqueue_LocatorService.php')), 'default', 'enqueue.client.%s.driver');

$instance->setName('enqueue:routes');

return $instance;
