<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.default.lazy_producer' shared service.

include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ProducerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Client/LazyProducer.php';

return $this->privates['enqueue.client.default.lazy_producer'] = new \Enqueue\Symfony\Client\LazyProducer(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'enqueue.client.default.producer' => ['services', 'enqueue.client.default.producer', 'getEnqueue_Client_Default_ProducerService.php', true],
], [
    'enqueue.client.default.producer' => '?',
]), 'enqueue.client.default.producer');
