<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.transport.default.queue_consumer' shared service.

include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/QueueConsumerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/QueueConsumer.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/StartExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/PreSubscribeExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/PreConsumeExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/MessageReceivedExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/PostMessageReceivedExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/MessageResultExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/ProcessorExceptionExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/PostConsumeExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/EndExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/InitLoggerExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/ExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/ChainExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/Extension/LogExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/Extension/ReplyExtension.php';

return $this->privates['enqueue.transport.default.queue_consumer'] = new \Enqueue\Consumption\QueueConsumer(($this->privates['enqueue.transport.default.context'] ?? $this->load('getEnqueue_Transport_Default_ContextService.php')), new \Enqueue\Consumption\ChainExtension([0 => ($this->privates['enqueue.consumption.reply_extension'] ?? ($this->privates['enqueue.consumption.reply_extension'] = new \Enqueue\Consumption\Extension\ReplyExtension())), 1 => new \Enqueue\Consumption\Extension\LogExtension()]), [], ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), 10000);
