<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.transport.default.connection_factory' shared service.

include_once \dirname(__DIR__, 4).'/vendor/queue-interop/queue-interop/src/ConnectionFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/ConnectionFactoryFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Doctrine/DoctrineConnectionFactoryFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/ConnectionFactoryFactory.php';

return $this->privates['enqueue.transport.default.connection_factory'] = (new \Enqueue\Doctrine\DoctrineConnectionFactoryFactory(($this->services['doctrine'] ?? $this->getDoctrineService()), new \Enqueue\ConnectionFactoryFactory()))->create(['dsn' => $this->getEnv('resolve:ENQUEUE_DSN')]);
