<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'enqueue_elastica.queue_pager_perister' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/PagerPersisterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/elastica-bundle/Persister/QueuePagerPersister.php';

return $this->services['enqueue_elastica.queue_pager_perister'] = new \Enqueue\ElasticaBundle\Persister\QueuePagerPersister(($this->privates['enqueue.transport.default.context'] ?? $this->load('getEnqueue_Transport_Default_ContextService.php')), ($this->services['fos_elastica.persister_registry'] ?? $this->load('getFosElastica_PersisterRegistryService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
