<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'enqueue.client.default.producer' shared service.

include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ProducerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/Producer.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Rpc/RpcFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/PreSendEventExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/PreSendCommandExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/DriverPreSendExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/PostSendExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ChainExtension.php';

return $this->services['enqueue.client.default.producer'] = new \Enqueue\Client\Producer(($this->privates['enqueue.client.default.driver'] ?? $this->load('getEnqueue_Client_Default_DriverService.php')), new \Enqueue\Rpc\RpcFactory(($this->privates['enqueue.client.default.context'] ?? $this->load('getEnqueue_Client_Default_ContextService.php'))), new \Enqueue\Client\ChainExtension([]));
