<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.default.router_processor' shared service.

include_once \dirname(__DIR__, 4).'/vendor/queue-interop/queue-interop/src/Processor.php';
include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/RouterProcessor.php';

return $this->privates['enqueue.client.default.router_processor'] = new \Enqueue\Client\RouterProcessor(($this->privates['enqueue.client.default.driver'] ?? $this->load('getEnqueue_Client_Default_DriverService.php')));
