<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.object_persister.tables.table' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersisterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersister.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/ModelToElasticaTransformerInterface.php';
include_once \dirname(__DIR__, 4).'/src/Elastica/Transformer/TableToElasticaTransformer.php';

return $this->services['fos_elastica.object_persister.tables.table'] = new \FOS\ElasticaBundle\Persister\ObjectPersister(($this->services['fos_elastica.index.tables.table'] ?? $this->getFosElastica_Index_Tables_TableService()), new \App\Elastica\Transformer\TableToElasticaTransformer(), 'App\\Entity\\Table', [], []);
