<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.persister_registry' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/PersisterRegistry.php';

$this->services['fos_elastica.persister_registry'] = $instance = new \FOS\ElasticaBundle\Persister\PersisterRegistry(['occurrences' => ['occurrence' => 'fos_elastica.object_persister.occurrences.occurrence'], 'photos' => ['photo' => 'fos_elastica.object_persister.photos.photo'], 'tables' => ['table' => 'fos_elastica.object_persister.tables.table'], 'observers' => ['observer' => 'fos_elastica.object_persister.observers.observer'], 'biblio_phytos' => ['biblio_phyto' => 'fos_elastica.object_persister.biblio_phytos.biblio_phyto']]);

$instance->setContainer($this);

return $instance;
