<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_elastica.populate_listener' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/EventListener/PopulateListener.php';

return $this->privates['fos_elastica.populate_listener'] = new \FOS\ElasticaBundle\EventListener\PopulateListener(($this->services['fos_elastica.resetter'] ?? $this->load('getFosElastica_ResetterService.php')));
