<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_elastica.command.templates_reset' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Command/ResetTemplatesCommand.php';

$this->privates['fos_elastica.command.templates_reset'] = $instance = new \FOS\ElasticaBundle\Command\ResetTemplatesCommand(($this->services['fos_elastica.template_resetter'] ?? $this->load('getFosElastica_TemplateResetterService.php')));

$instance->setName('fos:elastica:reset-templates');

return $instance;
