<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_elastica.doctrine.register_listeners' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/RegisterListenersService.php';

return $this->privates['fos_elastica.doctrine.register_listeners'] = new \FOS\ElasticaBundle\Doctrine\RegisterListenersService(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
