<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.template_resetter' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Index/ResetterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Index/TemplateResetter.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Index/MappingBuilder.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Index/IndexTemplateManager.php';

return $this->services['fos_elastica.template_resetter'] = new \FOS\ElasticaBundle\Index\TemplateResetter(($this->services['fos_elastica.config_manager.index_templates'] ?? $this->load('getFosElastica_ConfigManager_IndexTemplatesService.php')), ($this->privates['fos_elastica.mapping_builder'] ?? ($this->privates['fos_elastica.mapping_builder'] = new \FOS\ElasticaBundle\Index\MappingBuilder())), ($this->services['fos_elastica.client.default'] ?? $this->getFosElastica_Client_DefaultService()), ($this->services['fos_elastica.index_template_manager'] ?? ($this->services['fos_elastica.index_template_manager'] = new \FOS\ElasticaBundle\Index\IndexTemplateManager([]))));
