<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.object_persister.biblio_phytos.biblio_phyto' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersisterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersister.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/ModelToElasticaTransformerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/ModelToElasticaAutoTransformer.php';

$a = new \FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer(['identifier' => 'id', 'index' => 'biblio_phytos'], ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
$a->setPropertyAccessor(($this->privates['fos_elastica.property_accessor'] ?? ($this->privates['fos_elastica.property_accessor'] = new \Symfony\Component\PropertyAccess\PropertyAccessor(false, false))));

return $this->services['fos_elastica.object_persister.biblio_phytos.biblio_phyto'] = new \FOS\ElasticaBundle\Persister\ObjectPersister(($this->services['fos_elastica.index.biblio_phytos.biblio_phyto'] ?? $this->getFosElastica_Index_BiblioPhytos_BiblioPhytoService()), $a, 'App\\Entity\\BiblioPhyto', ['id' => [], 'title' => []], []);
