<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\DataProvider\PhotoCollectionDataProvider' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
include_once \dirname(__DIR__, 4).'/src/DataProvider/BaseCollectionDataProvider.php';
include_once \dirname(__DIR__, 4).'/src/DataProvider/PhotoCollectionDataProvider.php';

return $this->privates['App\\DataProvider\\PhotoCollectionDataProvider'] = new \App\DataProvider\PhotoCollectionDataProvider(($this->privates['security.helper'] ?? $this->getSecurity_HelperService()), ($this->services['fos_elastica.manager.orm'] ?? $this->getFosElastica_Manager_OrmService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
