<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ServeZippedPhotosAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/ServeZippedPhotosAction.php';

return $this->services['App\\Controller\\ServeZippedPhotosAction'] = new \App\Controller\ServeZippedPhotosAction(($this->privates['vich_uploader.storage.file_system'] ?? $this->getVichUploader_Storage_FileSystemService()), ($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()));
