<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'vich_uploader.mappings.media_object.directory_namer' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/Naming/DirectoryNamerInterface.php';
include_once \dirname(__DIR__, 4).'/src/Vich/TelaDirectoryNamer.php';

return $this->services['vich_uploader.mappings.media_object.directory_namer'] = new \App\Vich\TelaDirectoryNamer();
