<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIHxreSb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIHxreSb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIHxreSb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIHxreSb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIHxreSb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IHxreSb',
    'container.build_id' => 'fb4bc84f',
    'container.build_time' => 1589895326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIHxreSb');
