<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProjectSettings extends \App\Entity\ProjectSettings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'projectName', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'title', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'language', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'description', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'taxoRestrictionValue', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'type', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'isType', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'cssStyle', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'imageFont', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'dateCreated', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'dateUpdated', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'taxoRestrictionType', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'locationType', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'location', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'environment', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'info', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'publishedLocation', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'projectTagName', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'project'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'projectName', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'title', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'language', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'description', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'taxoRestrictionValue', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'type', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'isType', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'cssStyle', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'imageFont', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'dateCreated', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'dateUpdated', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'taxoRestrictionType', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'locationType', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'location', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'environment', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'info', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'publishedLocation', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'projectTagName', '' . "\0" . 'App\\Entity\\ProjectSettings' . "\0" . 'project'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProjectSettings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        return parent::onPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(?string $title): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo(?string $logo): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage(?string $language): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxoRestrictionValue(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxoRestrictionValue', []);

        return parent::getTaxoRestrictionValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxoRestrictionValue(?string $taxoRestrictionValue): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxoRestrictionValue', [$taxoRestrictionValue]);

        return parent::setTaxoRestrictionValue($taxoRestrictionValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(?string $type): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getCssStyle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCssStyle', []);

        return parent::getCssStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCssStyle(?string $cssStyle): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCssStyle', [$cssStyle]);

        return parent::setCssStyle($cssStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFont', []);

        return parent::getImageFont();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFont(?string $imageFont): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFont', [$imageFont]);

        return parent::setImageFont($imageFont);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfo', []);

        return parent::getInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfo(string $info): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfo', [$info]);

        return parent::setInfo($info);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated(\DateTimeInterface $dateCreated): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', [$dateCreated]);

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdated', []);

        return parent::getDateUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdated(?\DateTimeInterface $dateUpdated): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdated', [$dateUpdated]);

        return parent::setDateUpdated($dateUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxoRestrictionType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxoRestrictionType', []);

        return parent::getTaxoRestrictionType();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxoRestrictionType($taxoRestrictionType): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxoRestrictionType', [$taxoRestrictionType]);

        return parent::setTaxoRestrictionType($taxoRestrictionType);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalisationType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalisationType', []);

        return parent::getLocalisationType();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalisationType($localisationType): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalisationType', [$localisationType]);

        return parent::setLocalisationType($localisationType);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectName', []);

        return parent::getProjectName();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectName($projectName): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectName', [$projectName]);

        return parent::setProjectName($projectName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvironments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvironments', []);

        return parent::getEnvironments();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvironments($environments): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvironments', [$environments]);

        return parent::setEnvironments($environments);
    }

    /**
     * {@inheritDoc}
     */
    public function getProject(): ?\App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProject', []);

        return parent::getProject();
    }

    /**
     * {@inheritDoc}
     */
    public function setProject(?\App\Entity\TelaBotanicaProject $project): \App\Entity\ProjectSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProject', [$project]);

        return parent::setProject($project);
    }

}
