<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SyntheticColumn extends \App\Entity\SyntheticColumn implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'id', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'userEmail', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'userPseudo', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'sye', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . '_table', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'validations', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'items', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'vlBiblioSource', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'vlWorkspace'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'id', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'userEmail', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'userPseudo', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'sye', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . '_table', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'validations', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'items', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'vlBiblioSource', '' . "\0" . 'App\\Entity\\SyntheticColumn' . "\0" . 'vlWorkspace'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SyntheticColumn $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId(?int $userId): \App\Entity\OwnedEntitySimpleInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEmail', []);

        return parent::getUserEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserEmail(?string $userEmail): \App\Entity\OwnedEntityFullInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserEmail', [$userEmail]);

        return parent::setUserEmail($userEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPseudo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPseudo', []);

        return parent::getUserPseudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPseudo(?string $userPseudo): \App\Entity\OwnedEntityFullInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPseudo', [$userPseudo]);

        return parent::setUserPseudo($userPseudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSye(): ?\App\Entity\Sye
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSye', []);

        return parent::getSye();
    }

    /**
     * {@inheritDoc}
     */
    public function setSye(?\App\Entity\Sye $sye): \App\Entity\SyntheticColumn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSye', [$sye]);

        return parent::setSye($sye);
    }

    /**
     * {@inheritDoc}
     */
    public function getTable(): ?\App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTable', []);

        return parent::getTable();
    }

    /**
     * {@inheritDoc}
     */
    public function setTable(?\App\Entity\Table $_table): \App\Entity\SyntheticColumn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTable', [$_table]);

        return parent::setTable($_table);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidations', []);

        return parent::getValidations();
    }

    /**
     * {@inheritDoc}
     */
    public function addValidation(\App\Entity\OccurrenceValidation $validation): \App\Entity\SyntheticColumn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addValidation', [$validation]);

        return parent::addValidation($validation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeValidation(\App\Entity\OccurrenceValidation $validation): \App\Entity\SyntheticColumn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeValidation', [$validation]);

        return parent::removeValidation($validation);
    }

    /**
     * {@inheritDoc}
     */
    public function getItems(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', []);

        return parent::getItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addItem(\App\Entity\SyntheticItem $item): \App\Entity\SyntheticColumn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItem', [$item]);

        return parent::addItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItem(\App\Entity\SyntheticItem $item): \App\Entity\SyntheticColumn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItem', [$item]);

        return parent::removeItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlBiblioSource(): ?\App\Entity\BiblioPhyto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlBiblioSource', []);

        return parent::getVlBiblioSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlBiblioSource(?\App\Entity\BiblioPhyto $biblioPhyto): \App\Entity\SyntheticColumn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlBiblioSource', [$biblioPhyto]);

        return parent::setVlBiblioSource($biblioPhyto);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlWorkspace(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlWorkspace', []);

        return parent::getVlWorkspace();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlWorkspace(?string $vlWorkspace): \App\Entity\SyntheticColumn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlWorkspace', [$vlWorkspace]);

        return parent::setVlWorkspace($vlWorkspace);
    }

}
