<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SyntheticItem extends \App\Entity\SyntheticItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'id', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'userEmail', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'userPseudo', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'layer', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'repository', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'repositoryIdNomen', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'repositoryIdTaxo', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'displayName', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'occurrencesCount', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'isOccurrenceCountEstimated', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'frequency', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'coef', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'minCoef', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'maxCoef', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'syntheticColumn'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'id', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'userEmail', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'userPseudo', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'layer', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'repository', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'repositoryIdNomen', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'repositoryIdTaxo', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'displayName', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'occurrencesCount', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'isOccurrenceCountEstimated', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'frequency', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'coef', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'minCoef', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'maxCoef', '' . "\0" . 'App\\Entity\\SyntheticItem' . "\0" . 'syntheticColumn'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SyntheticItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId(?int $userId): \App\Entity\OwnedEntitySimpleInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEmail', []);

        return parent::getUserEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserEmail(?string $userEmail): \App\Entity\OwnedEntityFullInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserEmail', [$userEmail]);

        return parent::setUserEmail($userEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPseudo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPseudo', []);

        return parent::getUserPseudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPseudo(?string $userPseudo): \App\Entity\OwnedEntityFullInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPseudo', [$userPseudo]);

        return parent::setUserPseudo($userPseudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLayer(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLayer', []);

        return parent::getLayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setLayer(string $layer): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLayer', [$layer]);

        return parent::setLayer($layer);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepository(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepository', []);

        return parent::getRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepository(string $repository): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepository', [$repository]);

        return parent::setRepository($repository);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepositoryIdNomen(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepositoryIdNomen', []);

        return parent::getRepositoryIdNomen();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepositoryIdNomen(?int $repositoryIdNomen): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepositoryIdNomen', [$repositoryIdNomen]);

        return parent::setRepositoryIdNomen($repositoryIdNomen);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepositoryIdTaxo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepositoryIdTaxo', []);

        return parent::getRepositoryIdTaxo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepositoryIdTaxo(?string $repositoryIdTaxo): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepositoryIdTaxo', [$repositoryIdTaxo]);

        return parent::setRepositoryIdTaxo($repositoryIdTaxo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', []);

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName(?string $displayName): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', [$displayName]);

        return parent::setDisplayName($displayName);
    }

    /**
     * {@inheritDoc}
     */
    public function getOccurrencesCount(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOccurrencesCount', []);

        return parent::getOccurrencesCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOccurrencesCount(int $occurrencesCount): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOccurrencesCount', [$occurrencesCount]);

        return parent::setOccurrencesCount($occurrencesCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOccurrenceCountEstimated(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOccurrenceCountEstimated', []);

        return parent::getIsOccurrenceCountEstimated();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOccurrenceCountEstimated(bool $isOccurrenceCountEstimated): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOccurrenceCountEstimated', [$isOccurrenceCountEstimated]);

        return parent::setIsOccurrenceCountEstimated($isOccurrenceCountEstimated);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrequency(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrequency', []);

        return parent::getFrequency();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrequency(float $frequency): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrequency', [$frequency]);

        return parent::setFrequency($frequency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoef(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoef', []);

        return parent::getCoef();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoef(?string $coef): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoef', [$coef]);

        return parent::setCoef($coef);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinCoef(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinCoef', []);

        return parent::getMinCoef();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinCoef(?string $minCoef): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinCoef', [$minCoef]);

        return parent::setMinCoef($minCoef);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxCoef(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxCoef', []);

        return parent::getMaxCoef();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxCoef(?string $maxCoef): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxCoef', [$maxCoef]);

        return parent::setMaxCoef($maxCoef);
    }

    /**
     * {@inheritDoc}
     */
    public function getSyntheticColumn(): ?\App\Entity\SyntheticColumn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSyntheticColumn', []);

        return parent::getSyntheticColumn();
    }

    /**
     * {@inheritDoc}
     */
    public function setSyntheticColumn(?\App\Entity\SyntheticColumn $syntheticColumn): \App\Entity\SyntheticItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSyntheticColumn', [$syntheticColumn]);

        return parent::setSyntheticColumn($syntheticColumn);
    }

}
