<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TelaBotanicaProject extends \App\Entity\TelaBotanicaProject implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'parent', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'label', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'isPrivate', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'projectSettings', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'occurrences', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'extendedFields', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'administratorProfiles'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'parent', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'label', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'isPrivate', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'projectSettings', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'occurrences', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'extendedFields', '' . "\0" . 'App\\Entity\\TelaBotanicaProject' . "\0" . 'administratorProfiles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TelaBotanicaProject $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel(string $label): \App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPrivate(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPrivate', []);

        return parent::getIsPrivate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPrivate(bool $isPrivate): \App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPrivate', [$isPrivate]);

        return parent::setIsPrivate($isPrivate);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent(): ?\App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(?\App\Entity\TelaBotanicaProject $parent): \App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectSettings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectSettings', []);

        return parent::getProjectSettings();
    }

    /**
     * {@inheritDoc}
     */
    public function addProjectSettings(\App\Entity\ProjectSettings $projectSettings): \App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProjectSettings', [$projectSettings]);

        return parent::addProjectSettings($projectSettings);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProjectSettings(\App\Entity\ProjectSettings $projectSettings): \App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProjectSettings', [$projectSettings]);

        return parent::removeProjectSettings($projectSettings);
    }

    /**
     * {@inheritDoc}
     */
    public function getOccurrences(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOccurrences', []);

        return parent::getOccurrences();
    }

    /**
     * {@inheritDoc}
     */
    public function addOccurrence(\App\Entity\Occurrence $occurrence): \App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOccurrence', [$occurrence]);

        return parent::addOccurrence($occurrence);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOccurrence(\App\Entity\Occurrence $occurrence): \App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOccurrence', [$occurrence]);

        return parent::removeOccurrence($occurrence);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtendedFields(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtendedFields', []);

        return parent::getExtendedFields();
    }

    /**
     * {@inheritDoc}
     */
    public function addExtendedField(\App\Entity\ExtendedField $extendedField): \App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExtendedField', [$extendedField]);

        return parent::addExtendedField($extendedField);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExtendedField(\App\Entity\ExtendedField $extendedField): \App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExtendedField', [$extendedField]);

        return parent::removeExtendedField($extendedField);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
