<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Table extends \App\Entity\Table implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
  'pdf' => NULL,
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
  'pdf' => NULL,
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        unset($this->pdf);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'userEmail', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'userPseudo', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'isDiagnosis', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'validations', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'createdBy', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'updatedBy', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'rowsDefinition', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'sye', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'syeOrder', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'syntheticColumn', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'description', 'pdf', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'vlBiblioSource', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'vlWorkspace'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'userEmail', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'userPseudo', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'isDiagnosis', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'validations', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'createdBy', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'updatedBy', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'rowsDefinition', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'sye', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'syeOrder', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'syntheticColumn', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'vlBiblioSource', '' . "\0" . 'App\\Entity\\Table' . "\0" . 'vlWorkspace'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Table $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->pdf);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId(?int $userId): \App\Entity\OwnedEntitySimpleInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEmail', []);

        return parent::getUserEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserEmail(?string $userEmail): \App\Entity\OwnedEntityFullInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserEmail', [$userEmail]);

        return parent::setUserEmail($userEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPseudo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPseudo', []);

        return parent::getUserPseudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPseudo(?string $userPseudo): \App\Entity\OwnedEntityFullInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPseudo', [$userPseudo]);

        return parent::setUserPseudo($userPseudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDiagnosis(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDiagnosis', []);

        return parent::getIsDiagnosis();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDiagnosis(bool $isDiagnosis): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDiagnosis', [$isDiagnosis]);

        return parent::setIsDiagnosis($isDiagnosis);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidations', []);

        return parent::getValidations();
    }

    /**
     * {@inheritDoc}
     */
    public function addValidation(\App\Entity\OccurrenceValidation $validation): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addValidation', [$validation]);

        return parent::addValidation($validation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeValidation(\App\Entity\OccurrenceValidation $validation): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeValidation', [$validation]);

        return parent::removeValidation($validation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(int $createdBy): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(?\DateTimeInterface $createdAt): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy(?int $updatedBy): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updatedBy]);

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(?\DateTimeInterface $updatedAt): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getRowsDefinition(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRowsDefinition', []);

        return parent::getRowsDefinition();
    }

    /**
     * {@inheritDoc}
     */
    public function addRowsDefinition(\App\Entity\TableRowDefinition $rowsDefinition): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRowsDefinition', [$rowsDefinition]);

        return parent::addRowsDefinition($rowsDefinition);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRowsDefinition(\App\Entity\TableRowDefinition $rowsDefinition): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRowsDefinition', [$rowsDefinition]);

        return parent::removeRowsDefinition($rowsDefinition);
    }

    /**
     * {@inheritDoc}
     */
    public function getSye(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSye', []);

        return parent::getSye();
    }

    /**
     * {@inheritDoc}
     */
    public function addSye(\App\Entity\Sye $sye): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSye', [$sye]);

        return parent::addSye($sye);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSye(\App\Entity\Sye $sye): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSye', [$sye]);

        return parent::removeSye($sye);
    }

    /**
     * {@inheritDoc}
     */
    public function getSyeOrder(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSyeOrder', []);

        return parent::getSyeOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setSyeOrder(?string $syeOrder): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSyeOrder', [$syeOrder]);

        return parent::setSyeOrder($syeOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getSyntheticColumn(): ?\App\Entity\SyntheticColumn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSyntheticColumn', []);

        return parent::getSyntheticColumn();
    }

    /**
     * {@inheritDoc}
     */
    public function setSyntheticColumn(?\App\Entity\SyntheticColumn $syntheticColumn): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSyntheticColumn', [$syntheticColumn]);

        return parent::setSyntheticColumn($syntheticColumn);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdf(): ?\App\Entity\PdfFile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdf', []);

        return parent::getPdf();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdf(?\App\Entity\PdfFile $pdfFile): ?\App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdf', [$pdfFile]);

        return parent::setPdf($pdfFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlBiblioSource(): ?\App\Entity\BiblioPhyto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlBiblioSource', []);

        return parent::getVlBiblioSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlBiblioSource(?\App\Entity\BiblioPhyto $biblioPhyto): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlBiblioSource', [$biblioPhyto]);

        return parent::setVlBiblioSource($biblioPhyto);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlWorkspace(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlWorkspace', []);

        return parent::getVlWorkspace();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlWorkspace(?string $vlWorkspace): \App\Entity\Table
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlWorkspace', [$vlWorkspace]);

        return parent::setVlWorkspace($vlWorkspace);
    }

}
