<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ExtendedField extends \App\Entity\ExtendedField implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'fieldId', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'projectName', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'dataType', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'isVisible', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'isEditable', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'isMandatory', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'minValue', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'maxValue', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'defaultValue', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'regexp', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'unit', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'filterStep', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'filterLogarithmic', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'project', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'extendedFieldOccurrences', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'extendedFieldTranslations'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'fieldId', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'projectName', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'dataType', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'isVisible', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'isEditable', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'isMandatory', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'minValue', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'maxValue', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'defaultValue', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'regexp', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'unit', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'filterStep', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'filterLogarithmic', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'project', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'extendedFieldOccurrences', '' . "\0" . 'App\\Entity\\ExtendedField' . "\0" . 'extendedFieldTranslations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ExtendedField $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataType', []);

        return parent::getDataType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataType(string $dataType): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataType', [$dataType]);

        return parent::setDataType($dataType);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsVisible(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsVisible', []);

        return parent::getIsVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsVisible(bool $isVisible): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsVisible', [$isVisible]);

        return parent::setIsVisible($isVisible);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsEditable(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsEditable', []);

        return parent::getIsEditable();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEditable(?bool $isEditable): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEditable', [$isEditable]);

        return parent::setIsEditable($isEditable);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsMandatory(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsMandatory', []);

        return parent::getIsMandatory();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMandatory(bool $isMandatory): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMandatory', [$isMandatory]);

        return parent::setIsMandatory($isMandatory);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinValue(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinValue', []);

        return parent::getMinValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinValue(?float $minValue): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinValue', [$minValue]);

        return parent::setMinValue($minValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxValue(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxValue', []);

        return parent::getMaxValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxValue(?float $maxValue): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxValue', [$maxValue]);

        return parent::setMaxValue($maxValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultValue(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultValue', []);

        return parent::getDefaultValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultValue(?string $defaultValue): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultValue', [$defaultValue]);

        return parent::setDefaultValue($defaultValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegexp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegexp', []);

        return parent::getRegexp();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegexp(?string $regexp): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegexp', [$regexp]);

        return parent::setRegexp($regexp);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnit(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnit', []);

        return parent::getUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnit(?string $unit): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnit', [$unit]);

        return parent::setUnit($unit);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterStep(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterStep', []);

        return parent::getFilterStep();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterStep(?float $filterStep): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterStep', [$filterStep]);

        return parent::setFilterStep($filterStep);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterLogarithmic(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterLogarithmic', []);

        return parent::getFilterLogarithmic();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterLogarithmic(?bool $filterLogarithmic): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterLogarithmic', [$filterLogarithmic]);

        return parent::setFilterLogarithmic($filterLogarithmic);
    }

    /**
     * {@inheritDoc}
     */
    public function getProject(): ?\App\Entity\TelaBotanicaProject
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProject', []);

        return parent::getProject();
    }

    /**
     * {@inheritDoc}
     */
    public function setProject(?\App\Entity\TelaBotanicaProject $project): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProject', [$project]);

        return parent::setProject($project);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldId', []);

        return parent::getFieldId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFieldId(?string $fieldId): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFieldId', [$fieldId]);

        return parent::setFieldId($fieldId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectName', []);

        return parent::getProjectName();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectName(?string $projectName): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectName', [$projectName]);

        return parent::setProjectName($projectName);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtendedFieldOccurrences(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtendedFieldOccurrences', []);

        return parent::getExtendedFieldOccurrences();
    }

    /**
     * {@inheritDoc}
     */
    public function addExtendedFieldOccurrence(\App\Entity\ExtendedFieldOccurrence $extendedFieldOccurrence): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExtendedFieldOccurrence', [$extendedFieldOccurrence]);

        return parent::addExtendedFieldOccurrence($extendedFieldOccurrence);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExtendedFieldOccurrence(\App\Entity\ExtendedFieldOccurrence $extendedFieldOccurrence): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExtendedFieldOccurrence', [$extendedFieldOccurrence]);

        return parent::removeExtendedFieldOccurrence($extendedFieldOccurrence);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtendedFieldTranslations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtendedFieldTranslations', []);

        return parent::getExtendedFieldTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function addExtendedFieldTranslation(\App\Entity\ExtendedFieldTranslation $extendedFieldTranslation): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExtendedFieldTranslation', [$extendedFieldTranslation]);

        return parent::addExtendedFieldTranslation($extendedFieldTranslation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExtendedFieldTranslation(\App\Entity\ExtendedFieldTranslation $extendedFieldTranslation): \App\Entity\ExtendedField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExtendedFieldTranslation', [$extendedFieldTranslation]);

        return parent::removeExtendedFieldTranslation($extendedFieldTranslation);
    }

}
